import SwiftUI

// Tri-lingual user-facing text (zh / en / pt) per MePonto harness rule #7.
// Default app language is Portuguese (Brazil-facing). The user can switch at
// runtime in Profile; the choice is persisted with @AppStorage.
enum AppLanguage: String, CaseIterable, Identifiable {
    case pt, en, zh
    var id: String { rawValue }

    var nativeName: String {
        switch self {
        case .pt: return "Português"
        case .en: return "English"
        case .zh: return "中文"
        }
    }

    var flag: String {
        switch self {
        case .pt: return "🇧🇷"
        case .en: return "🇺🇸"
        case .zh: return "🇨🇳"
        }
    }
}

final class LocalizationManager: ObservableObject {
    @AppStorage("app_language") private var stored: String = AppLanguage.pt.rawValue

    @Published var language: AppLanguage = .pt

    init() {
        language = AppLanguage(rawValue: stored) ?? .pt
    }

    func setLanguage(_ lang: AppLanguage) {
        language = lang
        stored = lang.rawValue
    }

    func t(_ key: String) -> String {
        L10n.table[language]?[key] ?? L10n.table[.pt]?[key] ?? key
    }
}

enum L10n {
    static let table: [AppLanguage: [String: String]] = [
        .pt: [
            "tab.home": "Início", "tab.wallet": "Carteira", "tab.shifts": "Turnos",
            "tab.mall": "Loja", "tab.map": "Mapa",
            "home.greeting": "Olá", "home.rider": "Entregador",
            "home.today": "Hoje", "home.earnings": "Ganhos ontem",
            "home.orders": "Pedidos (semana)", "home.points": "Pontos hoje",
            "home.performance": "Desempenho", "home.tsh": "Horas TSH",
            "home.ar": "Aceitação", "home.caa": "Cancelados",
            "home.performanceWeek": "Esta semana · pessoal (igual ao painel)",
            "home.missionsNote": "Definidas pelo painel de operações (meta + prêmio + período)",
            "home.missions": "Missões", "home.inbox": "Avisos",
            "home.cashLedger": "Extrato de caixa", "home.benefits": "Benefícios de parceiros",
            "home.tier": "Faixas de brilho", "home.scan": "Escanear QR",
            "member.title": "Meu plano", "member.level": "Nível",
            "member.score": "Pontuação", "member.benefit": "Benefício",
            "member.ponto": "Ponto", "member.leader": "Líder",
            "member.bairro": "Bairro", "member.id99": "ID 99",
            "shift.status.submitted": "Em análise", "shift.status.approved": "Aprovado",
            "shift.status.none": "Disponível", "shift.station": "Estação",
            "points.statement": "Extrato de pontos", "points.myQR": "Meu QR MePonto",
            "points.myQRHint": "Seu código de membro (identificação)",
            "points.invite": "Convide amigos e ganhe pontos",
            "points.inviteHint": "Pontos após o 1º pedido do amigo",
            "points.earn": "Crédito", "points.spend": "Resgate",
            "splash.tagline": "Cada entrega vira benefício",
            "admin.splash": "Tela de abertura", "admin.splashEnabled": "Mostrar abertura",
            "admin.splashTagline": "Slogan", "admin.splashDuration": "Duração (s)",
            "admin.splashNote": "Em produção, definido pelo painel MePonto (backend).",
            "admin.resetBackend": "Restaurar padrão do backend",
            "wallet.title": "Carteira", "wallet.available": "Disponível",
            "wallet.pending": "A liberar", "wallet.weeklyGoal": "Meta semanal",
            "wallet.withdraw": "Solicitar saque", "wallet.statement": "Extrato",
            "shifts.title": "Turnos", "shifts.available": "Disponíveis",
            "shifts.agenda": "Minha agenda", "shifts.subscribe": "Inscrever-se",
            "shifts.subscribed": "Inscrito", "shifts.spots": "vagas",
            "shifts.cancel": "Cancelar inscrição", "shifts.empty": "Sem turnos neste dia",
            "shifts.thisWeek": "Esta semana", "shifts.nextWeek": "Próxima semana",
            "shifts.pontoOnly": "Somente turnos do seu ponto",
            "shifts.hotzone": "Demanda", "shifts.critical": "Pico",
            "shifts.noPayNote": "A inscrição reserva vaga; a renda vem das entregas, sem valor garantido.",
            "mall.title": "Loja de pontos", "mall.balance": "Saldo de pontos",
            "mall.redeem": "Resgatar", "mall.redeemed": "Resgatado",
            "mall.insufficient": "Pontos insuficientes",
            "map.title": "Serviços próximos", "map.navigate": "Navegar",
            "map.discount": "Desconto", "map.service": "Serviço",
            "map.locating": "Localizando você…", "map.enableLocation": "Ative a localização para ver o que está perto",
            "map.rating": "Avaliação", "map.reviews": "Avaliações", "map.writeReview": "Avaliar",
            "map.yourRating": "Sua nota", "map.comment": "Comentário", "map.submit": "Enviar",
            "map.noReviews": "Sem avaliações ainda", "scan.partnerEarns": "Parceiro ganha",
            "support.title": "Suporte",
            "support.safety": "Segurança agora", "support.chat": "Falar com suporte",
            "support.account": "Conta e acesso", "support.faq": "Perguntas frequentes",
            "scan.title": "Escanear QR", "scan.hint": "Aponte para o QR do ponto ou parceiro",
            "scan.simulate": "Simular leitura", "scan.result": "Código lido",
            "scan.noCamera": "Câmera indisponível neste dispositivo",
            "scan.purpose": "Escaneie o QR do parceiro para desconto, ou do ponto para check-in.",
            "scan.scanPartner": "Parceiro · desconto", "scan.scanPonto": "Ponto · check-in",
            "scan.discountApplied": "Desconto aplicado", "scan.checkedIn": "Check-in registrado",
            "scan.serviceDiscount": "Desconto de serviço", "scan.pointsEarned": "Pontos ganhos",
            "scan.again": "Escanear de novo",
            "profile.title": "Perfil", "profile.language": "Idioma",
            "profile.appearance": "Aparência", "profile.system": "Sistema",
            "profile.dark": "Escuro", "profile.light": "Claro",
            "profile.personalInfo": "Dados pessoais", "profile.payout": "Dados de repasse",
            "profile.cpf": "CPF", "profile.pix": "Chave PIX", "profile.notSet": "Não preenchido",
            "profile.completePrompt": "Complete CPF e PIX para receber seus repasses.",
            "profile.save": "Salvar", "profile.saved": "Dados salvos",
            "profile.logout": "Sair", "common.seeAll": "Ver tudo",
            "common.done": "Concluir", "common.close": "Fechar",
            "common.retry": "Tentar de novo", "common.loading": "Carregando…",
            "common.prev": "Anterior", "common.next": "Próximo",
            "auth.title": "Entrar", "auth.subtitle": "Acesse com seu telefone",
            "home.guestBrowse": "Veja turnos, loja e mapa sem entrar.",
            "auth.id": "ID 99", "auth.password": "Senha", "auth.login": "Entrar",
            "auth.invalid": "ID ou senha inválidos",
            "auth.note": "Em produção, o acesso é pelo login único do PontoSys.",
            "auth.register": "Cadastrar", "auth.name": "Nome", "auth.phone": "Telefone",
            "auth.fillAll": "Preencha todos os campos", "auth.welcome": "Bem-vindo ao MePonto",
            "auth.guestPrompt": "Entre para ver conta, ganhos e agenda",
            "auth.gatedAction": "Entre para continuar", "profile.guest": "Visitante",
            "error.load": "Não foi possível carregar", "empty.generic": "Nada por aqui ainda",
        ],
        .en: [
            "tab.home": "Home", "tab.wallet": "Wallet", "tab.shifts": "Shifts",
            "tab.mall": "Store", "tab.map": "Map",
            "home.greeting": "Hi", "home.rider": "Rider",
            "home.today": "Today", "home.earnings": "Earnings (yesterday)",
            "home.orders": "Orders (week)", "home.points": "Points today",
            "home.performance": "Performance", "home.tsh": "TSH hours",
            "home.ar": "Acceptance", "home.caa": "Cancelled",
            "home.performanceWeek": "This week · personal (same as backend)",
            "home.missionsNote": "Set by the operations backend (target + reward + period)",
            "home.missions": "Missions", "home.inbox": "Inbox",
            "home.cashLedger": "Cash ledger", "home.benefits": "Partner benefits",
            "home.tier": "Tier preview", "home.scan": "Scan QR",
            "member.title": "My plan", "member.level": "Level",
            "member.score": "Score", "member.benefit": "Benefit",
            "member.ponto": "Station", "member.leader": "Leader",
            "member.bairro": "Area", "member.id99": "99 ID",
            "shift.status.submitted": "Under review", "shift.status.approved": "Approved",
            "shift.status.none": "Available", "shift.station": "Station",
            "points.statement": "Points statement", "points.myQR": "My MePonto QR",
            "points.myQRHint": "Your member identity code",
            "points.invite": "Invite friends, earn points",
            "points.inviteHint": "Points after your friend's first order",
            "points.earn": "Credit", "points.spend": "Redeem",
            "splash.tagline": "Every delivery becomes a benefit",
            "admin.splash": "Launch screen", "admin.splashEnabled": "Show launch screen",
            "admin.splashTagline": "Tagline", "admin.splashDuration": "Duration (s)",
            "admin.splashNote": "In production this is managed by the MePonto backend.",
            "admin.resetBackend": "Reset to backend default",
            "wallet.title": "Wallet", "wallet.available": "Available",
            "wallet.pending": "Pending", "wallet.weeklyGoal": "Weekly goal",
            "wallet.withdraw": "Request payout", "wallet.statement": "Statement",
            "shifts.title": "Shifts", "shifts.available": "Available",
            "shifts.agenda": "My agenda", "shifts.subscribe": "Subscribe",
            "shifts.subscribed": "Subscribed", "shifts.spots": "spots",
            "shifts.cancel": "Cancel signup", "shifts.empty": "No shifts this day",
            "shifts.thisWeek": "This week", "shifts.nextWeek": "Next week",
            "shifts.pontoOnly": "Only your station's shifts",
            "shifts.hotzone": "Demand", "shifts.critical": "Peak",
            "shifts.noPayNote": "Signing up reserves a spot; income comes from deliveries — no guaranteed pay.",
            "mall.title": "Points store", "mall.balance": "Points balance",
            "mall.redeem": "Redeem", "mall.redeemed": "Redeemed",
            "mall.insufficient": "Not enough points",
            "map.title": "Nearby services", "map.navigate": "Navigate",
            "map.discount": "Discount", "map.service": "Service",
            "map.locating": "Locating you…", "map.enableLocation": "Enable location to see what's nearby",
            "map.rating": "Rating", "map.reviews": "Reviews", "map.writeReview": "Write a review",
            "map.yourRating": "Your rating", "map.comment": "Comment", "map.submit": "Submit",
            "map.noReviews": "No reviews yet", "scan.partnerEarns": "Partner earns",
            "support.title": "Support",
            "support.safety": "Safety now", "support.chat": "Contact support",
            "support.account": "Account & access", "support.faq": "FAQ",
            "scan.title": "Scan QR", "scan.hint": "Point at the point or partner QR",
            "scan.simulate": "Simulate scan", "scan.result": "Code scanned",
            "scan.noCamera": "Camera unavailable on this device",
            "scan.purpose": "Scan a partner QR for a discount, or a station QR to check in.",
            "scan.scanPartner": "Partner · discount", "scan.scanPonto": "Station · check-in",
            "scan.discountApplied": "Discount applied", "scan.checkedIn": "Checked in",
            "scan.serviceDiscount": "Service discount", "scan.pointsEarned": "Points earned",
            "scan.again": "Scan again",
            "profile.title": "Profile", "profile.language": "Language",
            "profile.appearance": "Appearance", "profile.system": "System",
            "profile.dark": "Dark", "profile.light": "Light",
            "profile.personalInfo": "Personal info", "profile.payout": "Payout details",
            "profile.cpf": "CPF", "profile.pix": "PIX key", "profile.notSet": "Not set",
            "profile.completePrompt": "Complete your CPF and PIX to receive payouts.",
            "profile.save": "Save", "profile.saved": "Saved",
            "profile.logout": "Sign out", "common.seeAll": "See all",
            "common.done": "Done", "common.close": "Close",
            "common.retry": "Retry", "common.loading": "Loading…",
            "common.prev": "Previous", "common.next": "Next",
            "auth.title": "Sign in", "auth.subtitle": "Sign in with your phone",
            "home.guestBrowse": "Browse shifts, store and map without signing in.",
            "auth.id": "99 ID", "auth.password": "Password", "auth.login": "Sign in",
            "auth.invalid": "Invalid ID or password",
            "auth.note": "In production, access is via PontoSys single sign-on.",
            "auth.register": "Register", "auth.name": "Name", "auth.phone": "Phone",
            "auth.fillAll": "Fill in all fields", "auth.welcome": "Welcome to MePonto",
            "auth.guestPrompt": "Sign in to see your account, earnings and agenda",
            "auth.gatedAction": "Sign in to continue", "profile.guest": "Guest",
            "error.load": "Couldn't load", "empty.generic": "Nothing here yet",
        ],
        .zh: [
            "tab.home": "首页", "tab.wallet": "钱包", "tab.shifts": "班次",
            "tab.mall": "商城", "tab.map": "地图",
            "home.greeting": "你好", "home.rider": "骑手",
            "home.today": "今日", "home.earnings": "昨日收益",
            "home.orders": "订单(本周)", "home.points": "今日积分",
            "home.performance": "绩效", "home.tsh": "在线时长",
            "home.ar": "接单率", "home.caa": "取消单",
            "home.performanceWeek": "本周 · 个人(口径同主后台)",
            "home.missionsNote": "由运营后台设置(目标 + 奖励 + 周期)",
            "home.missions": "任务", "home.inbox": "消息",
            "home.cashLedger": "现金账本", "home.benefits": "合作商户权益",
            "home.tier": "等级预览", "home.scan": "扫码",
            "member.title": "我的会员", "member.level": "等级",
            "member.score": "等级分", "member.benefit": "权益",
            "member.ponto": "网点", "member.leader": "队长",
            "member.bairro": "片区", "member.id99": "99 ID",
            "shift.status.submitted": "审核中", "shift.status.approved": "已通过",
            "shift.status.none": "可报名", "shift.station": "站点",
            "points.statement": "积分流水", "points.myQR": "我的 MePonto 二维码",
            "points.myQRHint": "你的会员身份码",
            "points.invite": "邀请好友得积分",
            "points.inviteHint": "好友完成首单后到账",
            "points.earn": "入账", "points.spend": "兑换",
            "splash.tagline": "每一单都变成权益",
            "admin.splash": "启动页", "admin.splashEnabled": "显示启动页",
            "admin.splashTagline": "标语", "admin.splashDuration": "时长(秒)",
            "admin.splashNote": "正式环境由 MePonto 主后台下发配置。",
            "admin.resetBackend": "恢复后台默认",
            "wallet.title": "钱包", "wallet.available": "可用余额",
            "wallet.pending": "待结算", "wallet.weeklyGoal": "本周目标",
            "wallet.withdraw": "申请提现", "wallet.statement": "流水",
            "shifts.title": "班次", "shifts.available": "可报名",
            "shifts.agenda": "我的日程", "shifts.subscribe": "报名",
            "shifts.subscribed": "已报名", "shifts.spots": "个名额",
            "shifts.cancel": "取消报名", "shifts.empty": "当天暂无班次",
            "shifts.thisWeek": "本周", "shifts.nextWeek": "下周",
            "shifts.pontoOnly": "仅显示本网点名额",
            "shifts.hotzone": "热区", "shifts.critical": "高峰",
            "shifts.noPayNote": "报名只锁定名额;实际收入按完成订单计算,不保证金额。",
            "mall.title": "积分商城", "mall.balance": "积分余额",
            "mall.redeem": "兑换", "mall.redeemed": "已兑换",
            "mall.insufficient": "积分不足",
            "map.title": "附近服务点", "map.navigate": "导航",
            "map.discount": "折扣", "map.service": "服务类型",
            "map.locating": "正在定位…", "map.enableLocation": "开启定位查看周边服务点",
            "map.rating": "评分", "map.reviews": "评价", "map.writeReview": "写评价",
            "map.yourRating": "你的评分", "map.comment": "评论", "map.submit": "提交",
            "map.noReviews": "暂无评价", "scan.partnerEarns": "商户获得",
            "support.title": "支持",
            "support.safety": "立即求助", "support.chat": "联系客服",
            "support.account": "账号与安全", "support.faq": "常见问题",
            "scan.title": "扫码", "scan.hint": "对准网点或商户二维码",
            "scan.simulate": "模拟扫码", "scan.result": "已扫描",
            "scan.noCamera": "本设备无可用相机",
            "scan.purpose": "扫商户二维码得服务折扣;扫站点二维码签到得积分。",
            "scan.scanPartner": "扫商户 · 折扣", "scan.scanPonto": "扫站点 · 签到",
            "scan.discountApplied": "折扣已核销", "scan.checkedIn": "签到成功",
            "scan.serviceDiscount": "服务折扣", "scan.pointsEarned": "获得积分",
            "scan.again": "再次扫码",
            "profile.title": "我的", "profile.language": "语言",
            "profile.appearance": "外观", "profile.system": "跟随系统",
            "profile.dark": "深色", "profile.light": "浅色",
            "profile.personalInfo": "个人信息", "profile.payout": "提现信息",
            "profile.cpf": "CPF", "profile.pix": "PIX 收款码", "profile.notSet": "未填写",
            "profile.completePrompt": "请补全 CPF 与 PIX 才能接收提现。",
            "profile.save": "保存", "profile.saved": "已保存",
            "profile.logout": "退出登录", "common.seeAll": "查看全部",
            "common.done": "完成", "common.close": "关闭",
            "common.retry": "重试", "common.loading": "加载中…",
            "common.prev": "上一页", "common.next": "下一页",
            "auth.title": "登录", "auth.subtitle": "使用手机号登录",
            "home.guestBrowse": "浏览班次、商城与地图无需登录。",
            "auth.id": "99 ID", "auth.password": "密码", "auth.login": "登录",
            "auth.invalid": "ID 或密码无效",
            "auth.note": "正式环境通过 PontoSys 统一登录接入。",
            "auth.register": "注册", "auth.name": "姓名", "auth.phone": "手机号",
            "auth.fillAll": "请填写所有字段", "auth.welcome": "欢迎来到 MePonto",
            "auth.guestPrompt": "登录查看你的会员、收益与日程",
            "auth.gatedAction": "登录后继续", "profile.guest": "游客",
            "error.load": "加载失败", "empty.generic": "暂无数据",
        ],
    ]
}
